version: "3.8"
services:
  app:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - CONFIG_PATH=./config.yml
    ports:
      - "127.0.0.1:8080:8080"